[project]
name = "AISync"
version = "0.0.1"
description = "AISync is a Backend service for my portfolio"
authors = ["loctvl842 <loclepnvx@gmail.com>"]

[tool.ruff]
line-length = 120

[tool.black]
line-length = 120
