services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    command: "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./monitoring/prommetheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    network_mode: "host"

volumes:
  prometheus:
    driver: local
