"""Add document name for document collection

Revision ID: 3e43ee84444c
Revises: d1dc7afed44d
Create Date: 2024-07-10 13:48:09.400799

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e43ee84444c"
down_revision: Union[str, None] = "d1dc7afed44d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("doc_collection", sa.Column("document_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("doc_collection", "document_name")
    # ### end Alembic commands ###
