"""Setup document table

Revision ID: 5298a2bc1668
Revises: ec637a108242
Create Date: 2024-06-26 11:52:53.929792

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5298a2bc1668"
down_revision: Union[str, None] = "ec637a108242"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "doc_collection",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("doc_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("page_content", sa.String(), nullable=False),
        sa.Column("embedding", Vector(dim=768), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("doc_collection")
    # ### end Alembic commands ###
