[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "aisync-dev"
version = "0.1.0"
description = "AISync Dev"
authors = ["loctvl842 <loclepnvx@gmail.com>"]
readme = "README.md"
packages = [{ include = "aisync_dev" }]

[tool.poetry.dependencies]
python = "^3.12"
aisync = { path = "../core", develop = true }
fastapi = "^0.115.6"
websockets = "^14.1"
