[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/aisync_dev"]

[project]
name = "aisync-dev"
version = "0.0.1"
description = "AISync Dev"
authors = [{ name = "loctvl842", email = "loclepnvx@gmail.com" }]
readme = "README.md"
dependencies = [
  "aisync",           # local package (AISync Core)
  "fastapi>=0.115.6",
  "uvicorn>=0.34.0",
  "websockets>=14.1",
]
