[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/aisync"]

[project]
name = "aisync"
version = "0.0.1"
description = "AISync Core"
authors = [{ name = "loctvl842", email = "loclepnvx@gmail.com" }]
readme = "README.md"
dependencies = [
  "langchain>=0.3.7",
  "langgraph>=0.2.39",
  "pydantic-settings>=2.6.1",
  "loguru>=0.7.2",
  "tokencost>=0.1.16",
  "langchain-openai>=0.2.6",
  "langchain-google-genai>=2.0.7",
]

[tool.ruff]
line-length = 120
extend-include = ["*.ipynb"]

[tool.black]
line-length = 120
