[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "aisync"
version = "0.1.0"
description = "AISync"
authors = ["loctvl842 <loclepnvx@gmail.com>"]
readme = "README.md"
packages = [{ include = "aisync" }]

[tool.poetry.dependencies]
python = "^3.12"
langchain = "^0.3.7"
langgraph = "^0.2.39"
pydantic-settings = "^2.6.1"
loguru = "^0.7.2"
tokencost = "^0.1.16"
langchain-openai = "^0.2.6"

[tool.ruff]
line-length = 120
extend-include = ["*.ipynb"]

[tool.black]
line-length = 120
