[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/aisync_cli"]

[project]
name = "aisync-cli"
version = "0.0.1"
description = "AISync CLI"
authors = [{name = "loctvl842", email = "loclepnvx@gmail.com"}]
readme = "README.md"
dependencies = [
  "aisync", # local package (AISync Core)
  "click>=8.1.8",
  "fastapi>=0.115.8",
  "pathspec>=0.12.1",
  "uvicorn>=0.34.0",
  "watchfiles>=1.0.4",
  "websockets>=14.2",
]

[project.scripts]
aisync = "aisync_cli.cli:main"
